### ISSUE TITLE
setFlash class not found 

### ISSUE THREAD

**Issue by sanjoydesk** [cygnite/framework#14]
v1.2.5 throwing issue when we use setFlash() in controller. For example:

 $this->setFlash('success', 'User saved successfully!')
        ->redirectTo('user/index/');

throws (call_user_func_array()) warning as no setFlash() found in AbstractBaseController.php file.

**Comment by gnanakeethan** [comment]
@sanjoydesk  Is this problem fixed ?

Regards,
Gnanakeethan

**Comment by sanjoydesk** [comment]
Yes it is fixed. @gnanakeethan

**Comment by gnanakeethan** [comment]
I am closing this issue down.
