### ISSUE TITLE
Making Inflector Helper Statically Accessible

### ISSUE THREAD

**Issue by eric-clinton** [cygnite/framework#15]
Can see some part of the framework Inflector used statically and some place still object, not uniform.
As a part of Helpers why don't we make Inflector functions as static, which look much short and simple.
See here:
https://github.com/cygnite/framework/blob/master/src/Cygnite/Console/Command/GeneratorCommand.php#L109
and https://github.com/cygnite/framework/blob/master/src/Cygnite/Database/Query.php#L731
and many more places

**Comment by sanjoydesk** [comment]
Yes valid question. We need to do the change as soon as possible and make this update available for next major release.

**Comment by gnanakeethan** [comment]
Issue fixed by 82554d6 .
