### ISSUE TITLE
Base URL with SSL

### ISSUE THREAD

**Issue by ryanemitchell** [cygnite/framework#16]
Just getting started with Cygnite, looks great!  I'm going to love this framework.   In the default welcome.view I can't get the stylesheet or favico urls to use https when the index loads via https. Is there a way to force Asset::style and URl::getbase to use SSL?  

 Trying to force SSL with .htaccess methods throw me into a redirect loop.

**Comment by sanjoydesk** [comment]
@ryanemitchell thanks for your love! :+1: 

Please confirm. You are trying to access external stylesheet into the view or you are trying to run the project into "https://" based url ?

**Comment by ryanemitchell** [comment]
Hey Thanks! I'm using the project where SSL is enabled so with https url. The internal stylesheet and favico both are generated with http.  Other than adding guzzlehttp via composer this is a "fresh install".  

I've tried it on a few different servers with the same results.

**Comment by sanjoydesk** [comment]
Oh! So `Url::getBase(); ` what it returns for you ? If returns something like `http://your-domain.com` then can you please print below code into your server and tell me what is returning.

 `var_dump(stripos($_SERVER['SERVER_PROTOCOL'], 'https'))` and 
 `var_dump(stripos($_SERVER['REQUEST_SCHEME'], 'https'))`

**Comment by ryanemitchell** [comment]
Thank for the help.  I put this into welcome.view.php

```
echo 'urlbase: '. Url::getBase();
echo '<br>';
echo 'https: ';
            var_dump(stripos($_SERVER['SERVER_PROTOCOL'], 'https'));
echo '<br>';
echo 'http: ';
            var_dump(stripos($_SERVER['REQUEST_SCHEME'], 'https'));
```
When viewing https://rmmdev.****.com/ the result is:

urlbase: http://rmmdev.****.com/
https: bool(false) 
http: bool(false)

**Comment by sanjoydesk** [comment]
Ok so there is an issue. Can you please come to https://gitter.im/cygnite/framework chat. So that we can help each other and try to find the issue. 

Thanks @ryanemitchell

**Comment by gnanakeethan** [comment]
I see this issue as fixed. Lets close it right away.
