### ISSUE TITLE
Active Reord - INSERT functionality fails in v1.2.5

### ISSUE THREAD

**Issue by jhonbendar** [cygnite/framework#17]
I was testing CRUD using Cygnite CLI for the current version (v1.2.5) and found data are not inserting properly into database. Update functionality works well though. It was working perfect in earlier version (v1.2.4) but breaking down in current version. Need to be fixed soon.

**Comment by sanjoydesk** [comment]
Thanks! Jhon for the contribution. I have merged changes. :+1:

**Comment by gnanakeethan** [comment]
This issue seems solved and closed.
