### ISSUE TITLE
Discussions for moving toward 2.0

### ISSUE THREAD

**Issue by jhonbendar** [cygnite/framework#19]
Hello Mates,

I believe Cygnite has enough features to move forward to v2.0. I can see many efficient features added for last few months. I would like to start some discussion regarding version upgrade with some code changes, simplifications, feature removals, and potential feature additions etc. 

What about the minimal PHP version 5.4.x ?

I'd love to hear feedback on this and moving forward.

@sanjoydesk @gnanakeethan @cygnite

**Comment by sanjoydesk** [comment]
Hello Jhon, 

Thanks for the proposal. Make sense, yes we are on the track and towards v2.0.  There are very few changes remaining for the release, and another important feature is translation component,  was planning to implement before the v2.0 release. What is your opinion ?

Also there will be folder structure changes, of course that will not be part of v2.0. Regarding minimal php requirement I believe we also need to upgrade code base right.

**Comment by jhonbendar** [comment]
Hello,

Looks like Cygnite redesigned completely but we are still unable to met v2.0 ETA. Any blocking point guys ? 

@sanjoydesk @gnanakeethan

**Comment by gnanakeethan** [comment]
Hi @jhonbendar,

We're looking to completely cover up the unit tests and implement some form of lazy loading classes before releasing.

Certainly some hand is needed at covering tests for all the classes and setting up certain CI and syntax checking tools.


Regards,
Gnanakeethan

**Comment by sanjoydesk** [comment]
We are delayed but the flavour of v2.0 gonna be much better, architectural changes, new directory structure, many additional features added into core. Running final tests before we gonna release the major version 2.0. 

Try version 2.0...  Stay with us!! @jhonbendar @gnanakeethan  :+1:

**Comment by sanjoydesk** [comment]
Thanks for contributing. Released v2.0. You may test the framework and let us know the feedback. @jhonbendar
