### ISSUE TITLE
[v2.0-alpha.01] [RouteCollection - StaticRoutes] Cannot send headers, headers already sent Issue

### ISSUE THREAD

**Issue by eric-clinton** [cygnite/framework#39]
Hi,
I am facing issue using RouteCollection class for defining collection of static routes. I have defined my crud controller name for handling routes in the "**Apps/Routing/RouteCollection.php**" file, but when i try to access the controller action it throws exception "Cannot send headers, headers already sent". 

I am facing this issue only when I define crud controller for routes using RouteCollection method. If I add routes manually in the "**Apps\Routing\Routes.php**" file it works fine.

**Comment by sanjoydesk** [comment]
@eric-clinton It seems issue with only CRUD routes. However get, post routing works fine. We will fix it asap before the v2.0 final release.
