### ISSUE TITLE
v1.3.1 release is breaking when rendering views

### ISSUE THREAD

**Issue by knewmanTE** [cygnite/framework#51]
The [most recent](https://packagist.org/packages/cygnite/framework#v1.3.1) 1.x package of Cygnite that is being pulled from Composer has some inconsistencies that prevent a user from generating a view.

You can browse the repo at the commit listed on the Packagist website [here](https://github.com/cygnite/framework/tree/51fc6710ed9fa737d19850d14a8048bb82996b6c) (this is the latest commit on the v1.3.1 tag too, as you might expect). Of note are two classes: [CView](https://github.com/cygnite/framework/blob/51fc6710ed9fa737d19850d14a8048bb82996b6c/src/Cygnite/Mvc/View/CView.php#L388), which appears to have been updated to View in the most recent dev branch, and [Output](https://github.com/cygnite/framework/blob/51fc6710ed9fa737d19850d14a8048bb82996b6c/src/Cygnite/Mvc/View/Output.php), which had its `load()` function removed at this commit in place of `buffer`. But, as you can see in the CView link above, it is still expecting `Output::load` to be a function.

I'm not very familiar with how Composer or Packagist work, so I don't know what the best course of action would be to help fix this. I've just been working on fixing up one of the Cygnite tests over on the [Techempower Framework Benchmark](https://github.com/TechEmpower/FrameworkBenchmarks) and thought I'd let you know about the bug I found!

**Comment by sanjoydesk** [comment]
@knewmanTE  Yes I could see that. We are working towards releasing v2.0. Let me correct and send you a pull request and also will send you pull request for v2.0 few days from now.

Hope that fine with you. Please let me know when is the next benchmark release date ?

Thanks!

**Comment by knewmanTE** [comment]
@sanjoydesk awesome! Can't wait to see v2.0! We're hoping to release our round 13 benchmark pretty soon, so we're finalizing a stable branch for that release, but we should be able to get the updated v1.3.1 and probably v2.0 updates into the round 14 run!

**Comment by sanjoydesk** [comment]
Thanks @knewmanTE I have fixed the issues and seems like PR is passing now. Please have a look and merge it for round-13. And yes we can include v2.0 in round-14. 

[https://github.com/TechEmpower/FrameworkBenchmarks/pull/2132](url)

thank you!
