### ISSUE TITLE
Class 'Cygnite\Database\Connections\MySql' not found

### ISSUE THREAD

**Issue by nardnahcayaj** [cygnite/framework#97]
When tried to connect database with mysql , i faced an error Class not found.

![selection_018](https://cloud.githubusercontent.com/assets/5484217/18216060/0eb47a10-7172-11e6-91b4-498beea12678.png)

**Comment by sanjoydesk** [comment]
The code base didn't merge properly, [reference commit](https://github.com/cygnite/framework/commit/4ede01187630f45a118b314eb51332da498da494). Will push and merge the change again. Thanks! @nardnahcayaj
